name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential

    - name: Build for Linux
      run: cargo build --release
    
    - name: Archive Linux binary
      uses: actions/upload-artifact@v2
      with:
        name: linux-binary
        path: target/release/lim-linux

    - name: Set up Rust for macOS
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build for macOS
      run: cargo build --release
    
    - name: Archive macOS binary
      uses: actions/upload-artifact@v2
      with:
        name: macos-binary
        path: target/release/lim-mac

    - name: Set up Rust for Windows
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-msvc
    
    - name: Archive Windows binary
      uses: actions/upload-artifact@v2
      with:
        name: windows-binary
        path: target/release/lim-windows.exe
